### ISSUE TITLE
Error when saving an empty file

### ISSUE THREAD

**Issue by kuoe0** [kuoe0/vim-janitor#6]
Error message shows when saving an empty file.

```
"/tmp/74560b12a5cb3986a2fd5b717c4d3c8d" 0L, 0C written                                                                                                      
Error detected while processing function CleanUp:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kuoe0/Works/KuoE0-vim/plugged/vim-scavenger/plugin/scavenger.py", line 38, in wrapper_function
    new_cursor = action(*cur_cursor)
  File "/Users/kuoe0/Works/KuoE0-vim/plugged/vim-scavenger/plugin/scavenger.py", line 125, in clean_up
    clean_up_multiple_blank_lines()
  File "/Users/kuoe0/Works/KuoE0-vim/plugged/vim-scavenger/plugin/scavenger.py", line 38, in wrapper_function
    new_cursor = action(*cur_cursor)
  File "/Users/kuoe0/Works/KuoE0-vim/plugged/vim-scavenger/plugin/scavenger.py", line 66, in clean_up_multiple_blank_lines
    if not len(new_buffer[-1]):
"plugins.zsh" 0L, 0C written
Press ENTER or type command to continue
```

**Comment by kuoe0** [comment]
It seems to not happen.
